name: CI
on:
- push
jobs:
  test:
    strategy:
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install --yes \
          build-essential \
          meson
    - name: Configure
      env:
        CC: ${{ matrix.cc }}
      run: |
        meson setup build \
          -Db_lundef=false \
          -Dwerror=true \
          -Dtest=true \
          -Db_sanitize=address,undefined
    - name: Build
      run: |
         meson compile -vC build
    - name: Test
      env:
        MESON_TESTTHREADS: "1"
      run: |
        meson test -vC build
